# Generated by Django 2.0.3 on 2018-03-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=300)),
                ('game_id', models.IntegerField()),
                ('fetch_date', models.DateTimeField(verbose_name='date cached')),
            ],
        ),
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user_id', models.BigIntegerField()),
                ('owned_games', models.ManyToManyField(to='gamepicker.GameInfo')),
            ],
        ),
    ]
