# Generated by Django 2.0.3 on 2018-04-06 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0002_switch_to_utf8mb4_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date cached'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='fetch_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date cached'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='game_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='user_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
