# Generated by Django 2.0.3 on 2018-04-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0003_auto_20180406_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gamepicker.GameInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='owned_games',
            field=models.ManyToManyField(through='gamepicker.Ownership', to='gamepicker.GameInfo'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gamepicker.SteamUser'),
        ),
    ]
