# Generated by Django 2.0.3 on 2018-04-06 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=300)),
                ('game_id', models.IntegerField(db_index=True)),
                ('fetch_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date cached')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gamepicker.GameInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date cached')),
                ('owned_games', models.ManyToManyField(through='gamepicker.Ownership', to='gamepicker.GameInfo')),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gamepicker.SteamUser'),
        ),
    ]
