# Generated by Django 2.0.3 on 2018-03-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0001_initial'),
    ]

    operations = [
            migrations.RunSQL(
                sql=['ALTER TABLE gamepicker_gameinfo MODIFY game_name VARCHAR(300) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
                reverse_sql=['ALTER TABLE gamepicker_gameinfo MODIFY game_name VARCHAR(300)']
                ),
            migrations.RunSQL(
                sql=['ALTER TABLE gamepicker_steamuser MODIFY name VARCHAR(150) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
                reverse_sql=['ALTER TABLE gamepicker_steamuser MODIFY name VARCHAR(150)']
                ),
            migrations.RunSQL(
                sql=['ALTER TABLE django_admin_log MODIFY object_repr VARCHAR(200) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
                reverse_sql=['ALTER TABLE django_admin_log MODIFY object_repr VARCHAR(200)']
                ),
    ]
